# Generated by Django 5.2.6 on 2026-09-24 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_ml', models.CharField(blank=True, max_length=250)),
                ('budget', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Proposed', 'Proposed'), ('Approved', 'Approved'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('On hold', 'On hold')], default='Ongoing', max_length=50)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('start_date', models.CharField(blank=True, max_length=50)),
                ('expected_completion', models.CharField(blank=True, max_length=50)),
                ('contractor', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='locations.ward')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
