# Generated by Django 5.2.6 on 2026-09-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title_ml', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(default='General', max_length=100)),
                ('content', models.TextField()),
                ('published_date', models.DateField(auto_now_add=True)),
                ('urgent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CitizenService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ml', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('category_ml', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('description_ml', models.TextField(blank=True)),
                ('required_documents', models.JSONField(default=list)),
                ('procedure', models.TextField(blank=True)),
                ('fee', models.CharField(default='Free', max_length=150)),
                ('processing_time', models.CharField(max_length=100)),
                ('official_portal_url', models.URLField()),
            ],
        ),
    ]
