# Generated by Django 5.2.6 on 2026-09-24 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ml', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='MapPin', max_length=50)),
                ('color', models.CharField(default='#059669', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_ml', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('description_ml', models.TextField(blank=True)),
                ('address', models.CharField(max_length=350)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('opening_hours', models.CharField(blank=True, max_length=150)),
                ('verified', models.BooleanField(default=True)),
                ('is_accessible', models.BooleanField(default=True)),
                ('source', models.CharField(default='Anthoor Municipality', max_length=200)),
                ('image_url', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='facilities.category')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='locations.ward')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
