# Generated by Django 5.2.6 on 2026-09-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=350)),
                ('phone', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=4.5)),
                ('hours', models.CharField(default='8:00 AM - 8:00 PM', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Directory Entries',
                'ordering': ['-id'],
            },
        ),
    ]
