# Generated by Django 5.2.6 on 2026-09-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('name_ml', models.CharField(blank=True, max_length=150)),
                ('councillor', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('population', models.PositiveIntegerField(default=1000)),
                ('latitude', models.FloatField(default=11.9734)),
                ('longitude', models.FloatField(default=75.3852)),
                ('boundary_geojson', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
