# Generated by Django 5.2.6 on 2026-09-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivicIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=150)),
                ('ward', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=350)),
                ('reporter_name', models.CharField(blank=True, max_length=150)),
                ('reporter_phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Submitted', max_length=50)),
                ('tracking_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
